# this is an example of the Visual Studio Online Git AP
# as a demonstration of an API spec in YAML
swagger: '2.0'

info:
  title: VSO Git API
  description: Interact with a Git repository hosted in VSO
  version: "1.0-preview.1"

# host not specified, as does not support templating.
# host: {account}.visualstudio.com

# basePath not specified, as it does not support templating
# basePath: /defaultcollection/_apis/git/repositories/{repository}

# array of all schemes that your API supports
schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /pullrequests:
    get:
      # Operation spec: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject
      summary: Get a list of pull requests
      externalDocs: 
        description: API Reference
        url: https://www.visualstudio.com/integrate/api/git/pull-requests
      parameters:
        - name: api-version
          in: query
          description: Version of the API to use.
          required: true
          type: string
        - name: status
          in: query
          description: Return pull requests with a specific status.
          type: string
          default: Active
          # TODO: Fill in more parameters
      responses:
        200:
          description: A collection of pull requests
          schema:
            type: array
            items:
              format: string #TODO: fill in real object